### PR TITLE
[Done] First wheel build & upload to pypi

### PR DESCRIPTION
**Pull request by caspervdw**
Following up on #3

There were still some mistakes in the script.
I adapted the Appveyor and Travis settings so that only branches are built, not PRs. This to save some build time.

### CODE REVIEW

**Comment by caspervdw** [comment]
@jorisvandenbossche @mwtoews  Travis is done. 

I am having some trouble getting the `twine upload ... dist/*.whl` right on appveyor. I am a bit in the dark because I don't have windows to test on.

The latest commit might fix the issue.

I put the passwords in place so when this is merged, wheels are uploaded to PyPI

**Comment by jorisvandenbossche** [comment]
Seems to be working now! (the first builds are passing)

**Comment by mwtoews** [comment]
Nice! I can see the files being populated in real-time [here](https://test.pypi.org/project/pygeos/0.7/#files). I'll spot-check a few on a Windows Desktop...

**Comment by caspervdw** [comment]
It' s working! One thing I wonder is: do we have to do some optimization of the GEOS build? You can supply the compiler with optimization flags.

**Comment by mwtoews** [comment]
Yup, the Windows builds look fine. I spot-sampled Python 3.7 amd64 bundled with MS Visual Studio, and an embedded Python 3.8 win32 version. All tests pass the same as they do on AppVeyor. The same warnings about "measurement.py:112: RuntimeWarning: All-NaN slice encountered np.nanmin(b[..., 0])" are shown, which hopefully could be resolved for the next release.

As for optimisation, `build_geos.cmd` has `-DCMAKE_BUILD_TYPE=Release` which usually sets the "-O3" equivalent for the compiler.

**Review by mwtoews — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
For Appveyor there is `build_geos.cmd` which indeed uses Release BUILD_TYPE. But how is GEOS installed / built on travis?

**Comment by jorisvandenbossche** [comment]
Ah, I suppose it is using the `build_simple` from multibuild (https://github.com/matthew-brett/multibuild/blob/f55556c46be580a6e65b1e95cbb3ec38e8913ab9/library_builders.sh#L53-L73)

**Comment by mwtoews** [comment]
Good point, these should follow the extension argument [here](https://github.com/pygeos/pygeos-wheels/blob/master/config.sh#L6). <s>At minimum, this should add `-O2` to this line.</s>

**Comment by jorisvandenbossche** [comment]
It seems the Release build is the default: https://github.com/libgeos/geos/blob/master/CMakeLists.txt#L17

So at least the current linux/mac builds should do the same as on appveyor. But not sure if there are additional flags to pass to ensure best performance

**Comment by mwtoews** [comment]
`build_simple` uses the autotools approach (`./configure`, `make`, etc.), so it's a different build setup. I just checked, and I see that it too has decent defaults: `-g -O2`, so I'd say optimisation is covered for all of the wheels.

**Comment by jorisvandenbossche** [comment]
So let's merge this?

**Comment by caspervdw** [comment]
One more thing. GEOS is LGPL so we should include the license with the binary

https://github.com/libgeos/geos/blob/master/COPYING

**Comment by caspervdw** [comment]
I am sure of it now that we should. See https://github.com/pygeos/pygeos/pull/118

**Comment by jorisvandenbossche** [comment]
In theory, we only need to include it in the wheels?

**Comment by caspervdw** [comment]
I bumped to 0.7.1 because of the licensing issue. It's already on PyPI so this is ready to merge when the builds pass.

**Comment by caspervdw** [comment]
OSX tests are failing because of https://travis-ci.community/t/macos-build-an-error-occurred-while-generating-the-build-script/7684/15

It should be solved now, I restarted it.

**Comment by jorisvandenbossche** [comment]
I restarted again the ones that didn't start

**Comment by jorisvandenbossche** [comment]
They're on PyPI (https://pypi.org/project/pygeos/#files) !

**Pull request merged**
