### PR TITLE
RLS: 0.10.1

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@caspervdw the fact that travis/appveyor doesn't start any build isn't normal?

**Comment by caspervdw** [comment]
You should commit directly to the deploy-test branch instead of using your own fork.

**Comment by jorisvandenbossche** [comment]
OK, did that in https://github.com/pygeos/pygeos-wheels/pull/11

**Comment by caspervdw** [comment]
That’s odd, I can’t trigger it manually also. I am guessing it is an authorisation issue.

**Pull request closed without merging**
