### PR TITLE
RLS: 0.10.1

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Hmm, for some reason travis is not triggered: https://travis-ci.com/github/pygeos/pygeos-wheels/branches

**Comment by caspervdw** [comment]
That’s odd, I can’t trigger it manually also. I am guessing it is an authorisation issue.

**Comment by caspervdw** [comment]
I am unable to see what is going wrong currently from my phone. Next week I’ll have access to my computer again so then I can investigate further.

**Comment by caspervdw** [comment]
I contacted travis-ci and they told me I needed to select a plan for the pygeos organisation. I did that and it seems to be working now!

**Review by caspervdw — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks! 

(OK, then I will leave my attempts to get the cibuildwheel working for later ;))

**Comment by jorisvandenbossche** [comment]
OK, this uploaded the wheels, and I also manually uploaded the sdist archive. So the 0.10.1 release should be done now.

**Pull request merged**
